connect_client=['host','user','password']
get_interface = ['host']
execute_cli=['host','command']
add_interface=['host','name','description','ip','subnetmask']
delete_interface=['host','interface_name']